yolo_detector_node:
  ros__parameters:
    color_image_topic: /camera/color/image_raw
    #time_step: 0.033 timer test
    detect_timer_period: 0.033
    debug_vis: False
    debug_visualization: true
